chore: Change content of pagination button
Bitnoise/react-scheduler pull request #24
Opened 2023-08-03 07:26 UTC by piotrNBTN

2023-08-03 07:42 UTC, itlamb requested changes

2023-08-03 07:42 UTC, itlamb commented on src/components/PaginationButton/PaginationButton.tsx
> +  const renderText = () => {
Why not
```
<StyledText>{intent === 'next' ? A : B}</StyledText>
```
?

2023-08-03 07:42 UTC, itlamb commented on src/components/PaginationButton/PaginationButton.tsx
> +  const renderText = () => {
Or, if not directly in render, just constant instead of a function?

2023-08-03 14:08 UTC, itlamb approved these changes

2023-08-04 06:42 UTC, mGasiorek998 approved these changes

2023-08-04 06:43 UTC, merged